<?php

namespace App;

/**
 * Eloquent class to describe the categories table
 *
 * automatically generated by ModelGenerator.php
 */
class Categories extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'categories';

    public $timestamps = false;

    protected $fillable = ['category_name', 'category_status', 'category_image'];

    public function contents()
    {
        return $this->hasMany('App\Contents', 'category_id', 'id');
    }
}
