<?php namespace App;

/**
 * Eloquent class to describe the users table
 *
 * automatically generated by ModelGenerator.php
 */
class Users extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'users';

    protected $fillable = ['name', 'email', 'email_verified_at', 'password', 'remember_token'];

    public function getDates()
    {
        return ['email_verified_at'];
    }

    public function bookmarks()
    {
        return $this->hasMany('App\Bookmarks', 'user_id', 'id');
    }

    public function contents()
    {
        return $this->hasMany('App\Contents', 'user_id', 'id');
    }

    public function rolePivots()
    {
        return $this->hasMany('App\RolePivots', 'user_id', 'id');
    }

    public function roles()
    {
        return $this->belongsToMany('App\Roles');
    }
}
