<?php namespace App;

/**
 * Eloquent class to describe the advertisments table
 *
 * automatically generated by ModelGenerator.php
 */
class Advertisments extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'advertisments';

    public $timestamps = false;

    protected $fillable = ['advertisment_image', 'published_at'];

    public function getDates()
    {
        return ['published_at'];
    }

    public function contents()
    {
        return $this->belongsTo('App\Contents', 'content_id', 'id');
    }
}
