<?php namespace App;

/**
 * Eloquent class to describe the bookmarks table
 *
 * automatically generated by ModelGenerator.php
 */
class Bookmarks extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'bookmarks';

    public $timestamps = false;

    protected $fillable = ['bookmarked_at'];

    public function getDates()
    {
        return ['bookmarked_at'];
    }

    public function contents()
    {
        return $this->belongsTo('App\Contents', 'content_id', 'id');
    }

    public function users()
    {
        return $this->belongsTo('App\Users', 'user_id', 'id');
    }
}
