<?php namespace App;

/**
 * Eloquent class to describe the marketing_teams table
 *
 * automatically generated by ModelGenerator.php
 */
class MarketingTeams extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'marketing_teams';

    public $timestamps = false;

    protected $fillable = ['mt_name', 'mt_phone', 'mt_designation', 'mt_sector', 'mt_email'];
}
