<?php namespace App;

/**
 * Eloquent class to describe the roles table
 *
 * automatically generated by ModelGenerator.php
 */
class Roles extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'roles';

    public $timestamps = false;

    protected $fillable = ['role_name'];

    public function rolePivots()
    {
        return $this->hasMany('App\RolePivots', 'role_id', 'id');
    }
}
